# version: '3.8'

# services:
#   db:
#     image: postgres:14
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: welcome
#       POSTGRES_DB: testdb
#     ports:
#       - "7005:5432"  # Host:Container (expose to 7005 on host)

#   app:
#     build: .
#     ports:
#       - "3000:3000"  # Assuming your app runs on 3000 inside container
#     depends_on:
#       - db
#     volumes:
#       - .:/app
#     env_file:
#       - .env


# services:
#   db:
#     image: postgres:14
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: welcome
#       POSTGRES_DB: testdb
#     ports:
#       - "7005:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     depends_on:
#       db:
#         condition: service_healthy
#     volumes:
#       - .:/app
#     env_file:
#       - .env

# version: '3.8'

# services:
#   db:
#     image: postgres:14
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: welcome
#       POSTGRES_DB: testdb
#     ports:
#       - "7005:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     depends_on:
#       db:
#         condition: service_healthy
#     volumes:
#       - .:/app
#     env_file:
#       - .env

version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: welcome
      POSTGRES_DB: testdb
    ports:
      - "7005:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  postgres_data:



